/*
 * Copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.microsoft.playwright;

/** DO NOT EDIT this file, it's generated automatically when running 'generate_api.sh'. */
public enum Device {
  /* Generated */
  BLACKBERRY_Z30("BlackBerry Z30"),
  BLACKBERRY_Z30_LANDSCAPE("BlackBerry Z30 landscape"),
  BLACKBERRY_PLAYBOOK("Blackberry PlayBook"),
  BLACKBERRY_PLAYBOOK_LANDSCAPE("Blackberry PlayBook landscape"),
  GALAXY_NOTE_3("Galaxy Note 3"),
  GALAXY_NOTE_3_LANDSCAPE("Galaxy Note 3 landscape"),
  GALAXY_NOTE_II("Galaxy Note II"),
  GALAXY_NOTE_II_LANDSCAPE("Galaxy Note II landscape"),
  GALAXY_S_III("Galaxy S III"),
  GALAXY_S_III_LANDSCAPE("Galaxy S III landscape"),
  GALAXY_S5("Galaxy S5"),
  GALAXY_S5_LANDSCAPE("Galaxy S5 landscape"),
  JIOPHONE_2("JioPhone 2"),
  JIOPHONE_2_LANDSCAPE("JioPhone 2 landscape"),
  KINDLE_FIRE_HDX("Kindle Fire HDX"),
  KINDLE_FIRE_HDX_LANDSCAPE("Kindle Fire HDX landscape"),
  LG_OPTIMUS_L70("LG Optimus L70"),
  LG_OPTIMUS_L70_LANDSCAPE("LG Optimus L70 landscape"),
  MICROSOFT_LUMIA_550("Microsoft Lumia 550"),
  MICROSOFT_LUMIA_550_LANDSCAPE("Microsoft Lumia 550 landscape"),
  MICROSOFT_LUMIA_950("Microsoft Lumia 950"),
  MICROSOFT_LUMIA_950_LANDSCAPE("Microsoft Lumia 950 landscape"),
  NEXUS_10("Nexus 10"),
  NEXUS_10_LANDSCAPE("Nexus 10 landscape"),
  NEXUS_4("Nexus 4"),
  NEXUS_4_LANDSCAPE("Nexus 4 landscape"),
  NEXUS_5("Nexus 5"),
  NEXUS_5_LANDSCAPE("Nexus 5 landscape"),
  NEXUS_5X("Nexus 5X"),
  NEXUS_5X_LANDSCAPE("Nexus 5X landscape"),
  NEXUS_6("Nexus 6"),
  NEXUS_6_LANDSCAPE("Nexus 6 landscape"),
  NEXUS_6P("Nexus 6P"),
  NEXUS_6P_LANDSCAPE("Nexus 6P landscape"),
  NEXUS_7("Nexus 7"),
  NEXUS_7_LANDSCAPE("Nexus 7 landscape"),
  NOKIA_LUMIA_520("Nokia Lumia 520"),
  NOKIA_LUMIA_520_LANDSCAPE("Nokia Lumia 520 landscape"),
  NOKIA_N9("Nokia N9"),
  NOKIA_N9_LANDSCAPE("Nokia N9 landscape"),
  PIXEL_2("Pixel 2"),
  PIXEL_2_XL("Pixel 2 XL"),
  PIXEL_2_XL_LANDSCAPE("Pixel 2 XL landscape"),
  PIXEL_2_LANDSCAPE("Pixel 2 landscape"),
  IPAD_GEN_6("iPad (gen 6)"),
  IPAD_GEN_6_LANDSCAPE("iPad (gen 6) landscape"),
  IPAD_GEN_7("iPad (gen 7)"),
  IPAD_GEN_7_LANDSCAPE("iPad (gen 7) landscape"),
  IPAD_MINI("iPad Mini"),
  IPAD_MINI_LANDSCAPE("iPad Mini landscape"),
  IPAD_PRO_11("iPad Pro 11"),
  IPAD_PRO_11_LANDSCAPE("iPad Pro 11 landscape"),
  IPHONE_11("iPhone 11"),
  IPHONE_11_PRO("iPhone 11 Pro"),
  IPHONE_11_PRO_MAX("iPhone 11 Pro Max"),
  IPHONE_11_PRO_MAX_LANDSCAPE("iPhone 11 Pro Max landscape"),
  IPHONE_11_PRO_LANDSCAPE("iPhone 11 Pro landscape"),
  IPHONE_11_LANDSCAPE("iPhone 11 landscape"),
  IPHONE_6("iPhone 6"),
  IPHONE_6_PLUS("iPhone 6 Plus"),
  IPHONE_6_PLUS_LANDSCAPE("iPhone 6 Plus landscape"),
  IPHONE_6_LANDSCAPE("iPhone 6 landscape"),
  IPHONE_7("iPhone 7"),
  IPHONE_7_PLUS("iPhone 7 Plus"),
  IPHONE_7_PLUS_LANDSCAPE("iPhone 7 Plus landscape"),
  IPHONE_7_LANDSCAPE("iPhone 7 landscape"),
  IPHONE_8("iPhone 8"),
  IPHONE_8_PLUS("iPhone 8 Plus"),
  IPHONE_8_PLUS_LANDSCAPE("iPhone 8 Plus landscape"),
  IPHONE_8_LANDSCAPE("iPhone 8 landscape"),
  IPHONE_SE("iPhone SE"),
  IPHONE_SE_LANDSCAPE("iPhone SE landscape"),
  IPHONE_X("iPhone X"),
  IPHONE_X_LANDSCAPE("iPhone X landscape"),
  IPHONE_XR("iPhone XR"),
  IPHONE_XR_LANDSCAPE("iPhone XR landscape");

  private final String deviceName;

  Device(String deviceName) {
    this.deviceName = deviceName;
  }

  public String deviceName() {
    return deviceName;
  }
}
