ARG ACR_CACHE_PREFIX
FROM ${ACR_CACHE_PREFIX}ubuntu:jammy

ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=America/Los_Angeles
ARG DOCKER_IMAGE_NAME_TEMPLATE="mcr.microsoft.com/playwright/java:v%version%-jammy"
ARG UBUNTU_MIRROR_PREFIX

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# === INSTALL JDK and Maven ===

RUN find /etc/apt -type f \( -name '*.list' -o -name '*.sources' \) \
      -exec sed -i "s|http://archive.ubuntu.com|http://${UBUNTU_MIRROR_PREFIX}archive.ubuntu.com|g; s|http://ports.ubuntu.com|http://${UBUNTU_MIRROR_PREFIX}ports.ubuntu.com|g" {} + && \
    apt-get update && \
    apt-get install -y --no-install-recommends openjdk-25-jdk \
    # Install utilities required for downloading browsers
    wget \
    # Install utilities required for downloading driver
    unzip \
    # For the MSEdge install script
    gpg && \
    rm -rf /var/lib/apt/lists/* && \
    # Create the pwuser
    adduser pwuser

# Ubuntu 22.04 and earlier come with Maven 3.6.3 which fails with
# Java 25, so we install latest Maven from Apache instead.
RUN VERSION=3.9.12 && \
    wget -O - https://archive.apache.org/dist/maven/maven-3/$VERSION/binaries/apache-maven-$VERSION-bin.tar.gz | tar zxfv - -C /opt/ && \
    ln -s /opt/apache-maven-$VERSION/bin/mvn /usr/local/bin/

ARG PW_TARGET_ARCH
ENV JAVA_HOME=/usr/lib/jvm/java-25-openjdk-${PW_TARGET_ARCH}

# === BAKE BROWSERS INTO IMAGE ===

# Browsers will remain downloaded in `/ms-playwright`.
# Note: make sure to set 777 to the registry so that any user can access
# registry.

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

# Extract the Playwright driver into the image once so the library reuses it instead of unpacking
# it into /tmp on every launch. See https://github.com/microsoft/playwright-java/issues/1268.
ENV PLAYWRIGHT_DRIVER_DIR=/ms-playwright-driver

RUN mkdir /ms-playwright && \
    mkdir /tmp/pw-java

COPY . /tmp/pw-java

# The optional Maven settings secret routes dependency resolution through a mirror
# (see .azure-pipelines/publish-docker.yml).
RUN --mount=type=secret,id=mavensettings,target=/root/.m2/settings.xml,required=false \
    cd /tmp/pw-java && \
    mvn install -D skipTests --no-transfer-progress && \
    mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI \
                     -D exec.args="install-driver" -f playwright/pom.xml --no-transfer-progress && \
    DEBIAN_FRONTEND=noninteractive mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI \
                     -D exec.args="install-deps" -f playwright/pom.xml --no-transfer-progress && \
    mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI \
                     -D exec.args="install" -f playwright/pom.xml --no-transfer-progress && \
    mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI \
                     -D exec.args="mark-docker-image '${DOCKER_IMAGE_NAME_TEMPLATE}'" -f playwright/pom.xml --no-transfer-progress && \
    rm -rf /tmp/pw-java && \
    # Workaround for https://github.com/microsoft/playwright/issues/27313
    # While the gstreamer plugin load process can be in-process, it ended up throwing
    # an error that it can't have libsoup2 and libsoup3 in the same process because
    # libgstwebrtc is linked against libsoup2. So we just remove the plugin.
    if [ "$(uname -m)" = "aarch64" ]; then \
        rm /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstwebrtc.so; \
    else \
        rm /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstwebrtc.so; \
    fi && \
    chmod -R 777 $PLAYWRIGHT_BROWSERS_PATH && \
    chmod -R 777 $PLAYWRIGHT_DRIVER_DIR
