name: Verify API
on:
  push:
    branches: [ master ]
    paths:
      - 'scripts/*'
      - 'api-generator/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'scripts/**'
      - 'api-generator/**'
jobs:
  verify:
    timeout-minutes: 30
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Download drivers
        run: scripts/download_driver_for_all_platforms.sh
      - name: Regenerate APIs
        run: scripts/generate_api.sh
      - name: Verify API is up to date
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "ERROR: generated interfaces differ from the current sources:"
            git diff
            exit 1
          fi
